---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ferret
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/secureblue/kinoite-main-hardened
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    # repos:
    #  - https://copr.fedorainfracloud.org/coprs/secureblue/run0edit/repo/fedora-%OS_VERSION%/secureblue-run0edit-fedora-%OS_VERSION%.repo
    # - https://copr.fedorainfracloud.org/coprs/lilay/topgrade/
    # - https://copr.fedorainfracloud.org/coprs/ublue-os/packages/
    install:
      - rclone
      - fzf # for ujust
      - gum # for ujust
      - fastfetch
      - tuned # power mgmt
      - tuned-ppd # power mgmt
      - lm_sensors
      - lshw
      - ryzenadj
      - tailscale
      - sysstat
      - btop
      - duf
      - lzip
      - p7zip
      - p7zip-plugins
      - rar
      - glow
      - topgrade
      - stress-ng
      - snapper
      - btrfs-assistant
      - lsb_release
      - uupd
      # - ds-inhibit ?
      - hhd
      - hhd-ui
      - adjustor
      - powerbuttond
      
      
      
  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: user
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.kde.gwenview
          - org.kde.okular
          - org.kde.kcalc
          - org.kde.haruna
          - org.kde.filelight
          - com.usebottles.bottles
          - com.ranfdev.DistroShelf
      
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
