---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ferret
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/secureblue/kinoite-main-hardened
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
    - https://copr.fedorainfracloud.org/coprs/bazzite-org/bazzite/repo/fedora-%OS_VERSION%/bazzite-org-bazzite-fedora-%OS_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/lilay/topgrade/repo/fedora-%OS_VERSION%/lilay-topgrade-fedora-%OS_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/ublue-os/packages/repo/fedora-%OS_VERSION%/ublue-os-fedora-%OS_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/ublue-os/akmods/repo/fedora-%OS_VERSION%/ublue-akmods-fedora-%OS_VERSION%.repo
    - https://copr.fedorainfracloud.org/coprs/hhd-dev/hhd/repo/fedora-%OS_VERSION%/hhd-dev-hhd-fedora-%OS_VERSION%.repo
    install:
      - rclone
      - fzf # for ujust
      - gum # for ujust
      - fastfetch
      - tuned # power mgmt
      - tuned-ppd # power mgmt
      - ddcutil # power mgmt
      - lm_sensors
      - lshw
      - tailscale
      - sysstat
      - btop
      - duf
      - lzip
      - p7zip
      - p7zip-plugins
      - rar
      - glow
      - stress-ng
      - snapper
      - btrfs-assistant
      - lsb_release
      # - ds-inhibit ?
      #copr
      - hhd
      - hhd-ui
      - adjustor
      - powerbuttond
      - ryzenadj
      - topgrade
      - uupd
      - upower
      - upower-libs
      - vpower
#      - kmod-xone # xone not found
#      - xone-kmod-common
      - ryzen-smu
      - kmod-ryzen-smu
      - gpd-fan
      - kmod-gpd-fan

  - type: akmods
    install:
      - xone
      #- ryzen-smu
      #- gpd-fan
    
  - type: script
    scripts:
      - enabledisablepowerwakeupsservice.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
